<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Trivy Report — {{ .ArtifactName }}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
<style>
  :root{
    --bg:#0b1220; --panel:#071127; --muted:#98a6bd; --accent:#2dd4bf;
    --critical:#ef4444; --high:#f59e0b; --medium:#f97316; --low:#60a5fa;
    --white:#e6eef8;
  }
  body{font-family:Inter,system-ui,Segoe UI,Roboto,Arial; margin:0; color:var(--white); background:linear-gradient(180deg,#031226 0%, #071a2b 100%); padding:28px;}
  .wrap{max-width:1200px;margin:0 auto}
  header{display:flex;gap:16px;align-items:flex-start; margin-bottom:18px}
  h1{font-size:22px;margin:4px 0;color:var(--white)}
  .meta{color:var(--muted);font-size:13px}
  .badges{display:flex;gap:10px;margin-top:8px}
  .badge{padding:7px 12px;border-radius:999px;font-weight:700;font-size:13px}
  .b-total{background:linear-gradient(90deg,#0369a1,#0284c7); color:#e6f7ff}
  .b-critical{background:linear-gradient(90deg,#7f1d1d,#ef4444)}
  .b-high{background:linear-gradient(90deg,#92400e,#f59e0b); color:#08141a}
  .card{background:linear-gradient(180deg, rgba(255,255,255,0.02), rgba(255,255,255,0.01)); padding:14px;border-radius:12px;box-shadow:0 8px 24px rgba(2,6,23,0.6); margin-bottom:16px}
  .row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}
  .target{font-weight:700;color:var(--accent); font-size:15px}
  details{background:transparent;border-radius:8px;margin-top:10px}
  summary{list-style:none;cursor:pointer;padding:10px 12px;border-radius:8px;background:rgba(255,255,255,0.02);display:flex;align-items:center;justify-content:space-between}
  table{width:100%;border-collapse:collapse;margin-top:8px;font-size:13px}
  th,td{padding:10px 12px;text-align:left;border-bottom:1px solid rgba(255,255,255,0.03)}
  th{font-weight:700;color:var(--muted);text-transform:uppercase;font-size:12px}
  tbody tr:hover td{background:linear-gradient(90deg, rgba(45,212,191,0.03), transparent)}
  .sev-CRITICAL{color:var(--critical);font-weight:800}
  .sev-HIGH{color:var(--high);font-weight:800}
  .sev-MEDIUM{color:var(--medium);font-weight:700}
  .sev-LOW{color:var(--low);font-weight:700}
  .filters{display:flex;gap:8px;align-items:center;margin-top:8px}
  input.search{flex:1;padding:8px 10px;border-radius:8px;border:1px solid rgba(255,255,255,0.03);background:transparent;color:var(--white)}
  .pill{padding:6px 10px;border-radius:999px;background:rgba(255,255,255,0.02); color:var(--muted); font-weight:700}
  footer{margin-top:22px;color:var(--muted);font-size:13px}
  a.cve{color:var(--accent); text-decoration:none}
  @media (max-width:800px){ header{flex-direction:column;align-items:flex-start} table{font-size:12px} }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div style="flex:1">
      <h1>🔎 Trivy Security Report</h1>
      <div class="meta">Artifact: <strong>{{ .ArtifactName }}</strong> — Generated by Trivy</div>
      <div class="badges" id="badges">
        <div class="badge b-total" id="totalBadge">Total: 0</div>
        <div class="badge b-critical" id="critBadge">Critical: 0</div>
        <div class="badge b-high" id="highBadge">High: 0</div>
      </div>
    </div>
    <div style="display:flex;flex-direction:column;gap:6px;align-items:flex-end">
      <div class="pill">Trivy template: premium blue</div>
      <div class="meta">Tip: use search to filter</div>
    </div>
  </header>

  <div class="card">
    <div class="row">
      <div class="filters" style="width:100%">
        <input class="search" id="searchBox" placeholder="Filter by package, CVE id, or text...">
        <div class="pill" id="filterInfo">Showing: <strong>All</strong></div>
      </div>
    </div>
  </div>

  <!-- Results -->
  {{ range .Results }}
  <details open>
    <summary>
      <div class="row" style="gap:14px;align-items:center">
        <div class="target">📦 {{ .Target }}</div>
        <div class="meta" style="margin-left:12px">Vulnerabilities: {{ len .Vulnerabilities }}</div>
      </div>
    </summary>

    <div class="card">
      <table class="vuln-table" data-target="{{ .Target }}">
        <thead>
          <tr>
            <th style="width:160px">Vulnerability</th>
            <th style="width:100px">Severity</th>
            <th>Package</th>
            <th style="width:110px">Installed</th>
            <th style="width:110px">Fixed</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {{ range .Vulnerabilities }}
            <tr class="vuln-row" data-severity="{{ .Severity }}">
              <td><a class="cve" href="{{ if gt (len .References) 0 }}{{ index .References 0 }}{{ else }}#{{ end }}" target="_blank">{{ .VulnerabilityID }}</a></td>
              <td class="sev-{{ .Severity }}">{{ .Severity }}</td>
              <td>{{ .PkgName }}</td>
              <td>{{ .InstalledVersion }}</td>
              <td>{{ .FixedVersion }}</td>
              <td title="{{ .Title }}">{{ .Title }}</td>
            </tr>
          {{ end }}
        </tbody>
      </table>
    </div>
  </details>
  {{ end }}

  <footer>Generated on {{ now }}</footer>
</div>

<script>
(function(){
  function updateCounts(){
    const rows = Array.from(document.querySelectorAll('.vuln-row'));
    const total = rows.length;
    const crit = rows.filter(r => r.dataset.severity === 'CRITICAL').length;
    const high = rows.filter(r => r.dataset.severity === 'HIGH').length;
    document.getElementById('totalBadge').innerText = 'Total: ' + total;
    document.getElementById('critBadge').innerText = 'Critical: ' + crit;
    document.getElementById('highBadge').innerText = 'High: ' + high;
  }

  function filterRows(text){
    const q = text.trim().toLowerCase();
    const rows = Array.from(document.querySelectorAll('.vuln-row'));
    rows.forEach(r=>{
      const match = q === '' || r.innerText.toLowerCase().includes(q);
      r.style.display = match ? '' : 'none';
    });
  }

  document.getElementById('searchBox').addEventListener('input', function(e){
    filterRows(e.target.value);
    updateCounts();
  });

  updateCounts();
})();
</script>
</body>
</html>
