{{- /* Trivy HTML Report Template */ -}}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Trivy Scan Report - {{ .ArtifactName }}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 20px; background: #f6f7fb; }
  h1 { color: #1d3557; }
  h2 { margin-top: 30px; color: #457b9d; }
  table { border-collapse: collapse; width: 100%; margin-top: 12px; }
  table, th, td { border: 1px solid #cccccc; }
  th { background: #1d3557; color: #fff; padding: 8px; }
  td { padding: 8px; }
  .severity { padding: 6px 10px; border-radius: 6px; color: #fff; font-weight: bold; }
  .CRITICAL { background: #d00000; }
  .HIGH { background: #e85d04; }
  .MEDIUM { background: #faa307; }
  .LOW { background: #4cc9f0; }
  .UNKNOWN { background: #adb5bd; }
  .footer { margin-top: 40px; font-size: 13px; text-align: center; color: gray; }
</style>
</head>
<body>

<h1>🔍 Trivy Security Scan Report</h1>
<p><strong>Image:</strong> {{ .ArtifactName }}</p>
<p><strong>Generated on:</strong> {{ now }}</p>

{{- range .Results }}
  {{- if .Vulnerabilities }}
    <h2>🚨 {{ .Target }}</h2>
    <table>
      <tr>
        <th>Severity</th>
        <th>CVE ID</th>
        <th>Package</th>
        <th>Installed Version</th>
        <th>Fixed Version</th>
        <th>Title</th>
        <th>Reference</th>
      </tr>
      {{- range .Vulnerabilities }}
      <tr>
        <td><span class="severity {{ .Severity }}">{{ .Severity }}</span></td>
        <td>{{ .VulnerabilityID }}</td>
        <td>{{ .PkgName }}</td>
        <td>{{ .InstalledVersion }}</td>
        <td>{{ .FixedVersion }}</td>
        <td>{{ .Title }}</td>
        <td>
          {{- if .PrimaryURL }}
            <a href="{{ .PrimaryURL }}" target="_blank">Link</a>
          {{- else }}
            <a href="https://nvd.nist.gov/vuln/search/results?query={{ .VulnerabilityID }}" target="_blank">NVD</a>
          {{- end }}
        </td>
      </tr>
      {{- end }}
    </table>
  {{- end }}
{{- end }}

<div class="footer">
  Generated by Trivy — Secure your supply chain 🔐
</div>

</body>
</html>
#ssl_monitor_project\docker\trivy-reports\templates\html.tpl